Repository sergiodxa/remix-auth-form, pull requests merged in 2022-09, with the labels that each got.

#14 Use context.formData if available over request.formData()
  README.md
  src/index.ts
  test/index.test.ts
Labels: enhancement

#15 Require at least remix-auth 3.3.0
  package.json
Labels: dependencies

#16 Use `ActionArgs` instead of `ActionFunction`
  README.md
Labels: documentation
